ALTER TABLE SK_SYAIN
ADD SYASHIN_ID VARCHAR2(4) NOT NULL;

ALTER TABLE SK_SYAIN
ADD SYAIN_YUBIN VARCHAR2(7) NULL;

ALTER TABLE SK_SYAIN
ADD SYAIN_KEN VARCHAR2(5) NULL;

ALTER TABLE SK_SYAIN
ADD SYAIN_NYUSYA_YMD DATE NULL;

ALTER TABLE SK_SYAIN
ADD SYAIN_TAISYA_YMD DATE NULL;